if (NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT VARIABLE_NAME)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE and VARIABLE_NAME must be defined")
endif()

file(READ ${INPUT_FILE} SHADER_CONTENT)

string(REPLACE "\n" "\\n" SHADER_CONTENT "${SHADER_CONTENT}")
string(REPLACE "\r" "\\r" SHADER_CONTENT "${SHADER_CONTENT}")
string(REPLACE "\t" "\\t" SHADER_CONTENT "${SHADER_CONTENT}")

file(WRITE ${OUTPUT_FILE} "const char *${VARIABLE_NAME} = \"${SHADER_CONTENT}\";")