/* INTERNAL DEVELOPMENT TOOL -- not part of the permanent test suite, not
   registered with CTest, no exit-code contract to keep stable.

   WHAT: C1 (must_recalculate_normals=1) adaptation of splice_tess_field.c
   for the hand.stl Acrobat blank-model-tree investigation (see
   E:\Work\nanoPRC_supplementary_files\ISO-SPEC\
   hand-stl-acrobat-blanktree-investigation-22July.md for full context).
   Same technique as the original tool: take a REAL, Acrobat-working raw
   .prc file's PRC_TYPE_TESS_3D_Compressed entry and reproduce it FIELD BY
   FIELD, copying every field's raw bits verbatim from the real file EXCEPT
   for exactly one caller-selected field, which is instead regenerated
   fresh through this write facility's own production primitives, fed the
   real, decoded values for that field.

   The original tool hard-codes the C2 (must_recalculate_normals=0) field
   sequence and was built against a specific C2 test file (the hockey
   puck). This variant hard-codes the C1 sequence and field-value
   assertions matching hand-ic3d-extracted.prc specifically (the real,
   independently-produced, Acrobat-working encode of hand.stl):
   must_recalculate_normals=1, is_point_color=0, is_multiple_line_
   attribute=0, no_texture=1, has_behaviors=0. The C1-specific fields after
   must_recalculate_normals differ entirely from C2's: normal_is_reversed
   (a plain per-triangle bit array, NOT Huffman-compressed -- a different
   kind of candidate than the other five, which are all variable-bit-width/
   Huffman-compressed arrays), crease_angle, normal_recalculation_flags --
   replacing C2's normal_angle_number_of_bits/normal_binary_data_size/
   normal_binary_data/normal_angle_array/is_face_planar entirely (see
   prc_parse_tess.c ~lines 951-985 for the exact parser field order this
   mirrors, and prc_write_compress_tess.c's prc_write_compress_tess_to_
   stream for the writer side).

   HOW: usage: splice_tess_field_c1.exe <real_input.prc> <output.prc>
   [field_name]. field_name selects which single field gets regenerated by
   this write facility instead of copied verbatim; omit it (or pass
   "none") to copy every field verbatim, which should reproduce the real
   file's tessellation section bit-for-bit -- a self-check that this
   tool's field-walk is correct before trusting any non-"none" run.
   Recognized field_name values: point_array, edge_status_array,
   triangle_face_array, point_reference_array, normal_is_reversed,
   line_attribute_array.

   LIMITATIONS: hard-codes the field sequence and conditional branches
   matching hand-ic3d-extracted.prc specifically -- NOT a general C1 file
   tool. Only tests one field per run; run multiple times with different
   field_name values to bisect further. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "prc_data.h"
#include "prc_api.h"
#include "prc_context.h"
#include "prc_bit.h"
#include "prc_parse_tess.h"
#include "prc_parse_common.h"
#include "prc_write_compress_tess.h"
#include "prc_write_file_structure.h"
#include "prc_write_common.h"
#include "zlib.h"

static uint32_t read_le_u32(const uint8_t *p) { return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static void write_le_u32(uint8_t *p, uint32_t v) { p[0]=(uint8_t)(v&0xff); p[1]=(uint8_t)((v>>8)&0xff); p[2]=(uint8_t)((v>>16)&0xff); p[3]=(uint8_t)((v>>24)&0xff); }

typedef enum {
    FIELD_NONE = 0,
    FIELD_POINT_ARRAY,
    FIELD_EDGE_STATUS_ARRAY,
    FIELD_TRIANGLE_FACE_ARRAY,
    FIELD_POINT_REFERENCE_ARRAY,
    FIELD_NORMAL_IS_REVERSED,
    FIELD_LINE_ATTRIBUTE_ARRAY
} test_field_t;

static int
copy_bits(prc_context *ctx, prc_bit_state *src, prc_bit_write_state *dst, int64_t nbits)
{
    int64_t k;
    for (k = 0; k < nbits; k++)
    {
        uint8_t bit = prc_bitread_bit(ctx, src);
        if (prc_bitwrite_bit(ctx, dst, bit) != 0)
            return -1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    prc_context *ctx;
    FILE *fid;
    long fsize;
    uint8_t *buf;
    size_t read_size;
    const uint8_t *p;
    uint32_t section_count;
    uint32_t *section_offsets;
    uint32_t start_offset, end_offset;
    uint32_t i;
    size_t header_prefix_len;
    size_t section_off_table_byte_pos;
    uint8_t *tess_inflated = NULL;
    size_t dest_len_saved = 0;
    int code;
    prc_bit_state bit_state;
    uint32_t wrapper_tag;
    uint32_t tess_count;
    uint32_t entry_tag;
    prc_tess_3d_compressed *parsed = NULL;
    prc_bit_state entry_start;
    prc_bit_state replay;
    prc_bit_write_state ws;
    uint8_t *wrapper_comp = NULL;
    size_t wrapper_comp_len = 0;
    uint32_t k;
    uint32_t *new_section_offsets;
    uint32_t new_start_offset, new_end_offset;
    size_t new_total_size;
    uint8_t *out_buf;
    FILE *out_fid;
    test_field_t test_field = FIELD_NONE;
    uint32_t num_refs = 0;
    uint32_t face_count = 0;

    if (argc < 3)
    {
        printf("usage: %s <real_input.prc> <output.prc> [field_name]\n", argv[0]);
        printf("  field_name: point_array | edge_status_array | triangle_face_array |\n");
        printf("              point_reference_array | normal_is_reversed | line_attribute_array\n");
        printf("  (omit or \"none\" to copy every field verbatim -- self-check mode)\n");
        return 2;
    }
    if (argc >= 4)
    {
        if (strcmp(argv[3], "point_array") == 0) test_field = FIELD_POINT_ARRAY;
        else if (strcmp(argv[3], "edge_status_array") == 0) test_field = FIELD_EDGE_STATUS_ARRAY;
        else if (strcmp(argv[3], "triangle_face_array") == 0) test_field = FIELD_TRIANGLE_FACE_ARRAY;
        else if (strcmp(argv[3], "point_reference_array") == 0) test_field = FIELD_POINT_REFERENCE_ARRAY;
        else if (strcmp(argv[3], "normal_is_reversed") == 0) test_field = FIELD_NORMAL_IS_REVERSED;
        else if (strcmp(argv[3], "line_attribute_array") == 0) test_field = FIELD_LINE_ATTRIBUTE_ARRAY;
        else if (strcmp(argv[3], "none") == 0) test_field = FIELD_NONE;
        else { printf("unrecognized field_name '%s'\n", argv[3]); return 2; }
    }
    printf("Test field: %s\n", argc >= 4 ? argv[3] : "none (verbatim self-check)");

    fid = fopen(argv[1], "rb");
    if (fid == NULL) { printf("failed to open %s\n", argv[1]); return 1; }
    fseek(fid, 0L, SEEK_END);
    fsize = ftell(fid);
    fseek(fid, 0L, SEEK_SET);
    buf = (uint8_t *)malloc((size_t)fsize);
    read_size = fread(buf, 1, (size_t)fsize, fid);
    fclose(fid);
    if (read_size != (size_t)fsize) { printf("short read\n"); return 1; }
    if (memcmp(buf, "PRC", 3) != 0) { printf("not a raw PRC file\n"); return 1; }

    p = buf + 3 + 4 + 4 + 16 + 16;
    if (read_le_u32(p) != 1) { printf("only single-file-structure inputs supported\n"); return 1; }
    p += 4;
    p += 16; /* fs_uid */
    p += 4;  /* reserved */
    section_off_table_byte_pos = (size_t)(p - buf) + 4;
    section_count = read_le_u32(p); p += 4;
    header_prefix_len = (size_t)(p - buf);

    section_offsets = (uint32_t *)malloc(sizeof(uint32_t) * section_count);
    for (i = 0; i < section_count; i++) { section_offsets[i] = read_le_u32(p); p += 4; }
    start_offset = read_le_u32(p); p += 4;
    end_offset = read_le_u32(p); p += 4;

    if (section_count < 4) { printf("unexpected section_count=%u\n", section_count); return 1; }

    ctx = prc_api_new_context(NULL);
    if (ctx == NULL) { printf("context creation failed\n"); return 1; }

    /* Inflate the real tessellation section (section index 3: offsets[3]..offsets[4]) */
    {
        uLongf dest_len;
        uint32_t comp_len = section_offsets[4] - section_offsets[3];
        dest_len = comp_len * 40u + 4096u;
        tess_inflated = (uint8_t *)malloc(dest_len);
        for (;;)
        {
            uLongf try_len = dest_len;
            int zret = uncompress(tess_inflated, &try_len, buf + section_offsets[3], comp_len);
            if (zret == Z_OK) { dest_len = try_len; break; }
            if (zret == Z_BUF_ERROR) { dest_len *= 2; free(tess_inflated); tess_inflated = (uint8_t *)malloc(dest_len); continue; }
            printf("zlib uncompress failed: %d\n", zret);
            return 1;
        }
        dest_len_saved = (size_t)dest_len;
        prc_init_bit_state(ctx, &bit_state, tess_inflated, (size_t)dest_len);
    }

    wrapper_tag = prc_bitread_uint32(ctx, &bit_state);
    if (wrapper_tag != PRC_TYPE_ASM_FileStructureTessellation) { printf("unexpected wrapper tag %u\n", wrapper_tag); return 1; }
    {
        prc_content_prc_base wrapper_base;
        memset(&wrapper_base, 0, sizeof(wrapper_base));
        code = prc_parse_content_prc_base(ctx, &bit_state, &wrapper_base);
        if (code < 0) { printf("prc_parse_content_prc_base failed: code=%d\n", code); return 1; }
    }
    tess_count = prc_bitread_uint32(ctx, &bit_state);
    if (tess_count != 1) { printf("this tool only handles tess_count==1 files (got %u)\n", tess_count); return 1; }
    entry_tag = prc_bitread_uint32(ctx, &bit_state);
    if (entry_tag != PRC_TYPE_TESS_3D_Compressed) { printf("first entry is not COMPRESSED (tag=%u)\n", entry_tag); return 1; }

    entry_start = bit_state;

    code = prc_parse_tess_3d_compressed(ctx, &bit_state, &parsed, 0);
    if (code < 0) { printf("prc_parse_tess_3d_compressed failed: code=%d\n", code); return 1; }

    printf("Real: is_calculated=%u has_faces=%u point_array_size=%u edge_status_array_size=%u\n",
        parsed->is_calculated, parsed->has_faces, parsed->point_array_size, parsed->edge_status_array_size);
    printf("  triangle_face_array_size=%u face_number=%u reference_array_size=%u point_reference_array_size=%u\n",
        parsed->triangle_face_array_size, parsed->face_number, parsed->reference_array_size, parsed->point_reference_array_size);
    printf("  must_recalculate_normals=%u is_point_color=%u is_multiple_line_attribute=%u no_texture=%u has_behaviors=%u\n",
        parsed->must_recalculate_normals, parsed->is_point_color, parsed->is_multiple_line_attribute,
        parsed->no_texture, parsed->has_behaviors);
    if (!parsed->must_recalculate_normals || parsed->is_point_color || parsed->is_multiple_line_attribute ||
        !parsed->no_texture || parsed->has_behaviors)
    {
        printf("ERROR: this real file does not match the hard-coded C1/no-extras branch this tool assumes -- see LIMITATIONS. Aborting.\n");
        return 1;
    }
    for (k = 0; k < parsed->reference_array_size; k++)
        if (parsed->points_is_reference_array[k]) num_refs++;
    face_count = parsed->face_number;

    /* Diagnostic: normal_is_reversed histogram (how many 1s) */
    {
        uint32_t ones = 0;
        for (k = 0; k < parsed->triangle_face_array_size; k++)
            if (parsed->normal_is_reversed[k]) ones++;
        printf("normal_is_reversed: %u ones / %u\n", ones, parsed->triangle_face_array_size);
    }
    printf("crease_angle (radians, post-conversion)=%.17g normal_recalculation_flags=%u\n",
        parsed->crease_angle, parsed->normal_recalculation_flags);

    /* ---- Field-by-field replay + splice ---- */
    replay = entry_start;
    memset(&ws, 0, sizeof(ws));
    if (prc_bitwrite_init(ctx, &ws, 4096) != 0) { printf("wrapper init failed\n"); return 1; }
    if (prc_bitwrite_uint32(ctx, &ws, PRC_TYPE_ASM_FileStructureTessellation) != 0) { printf("write fail\n"); return 1; }
    if (prc_bitwrite_uint32(ctx, &ws, 0) != 0) { printf("write fail\n"); return 1; } /* attribute_count=0 */
    if (prc_bitwrite_bit(ctx, &ws, 1) != 0) { printf("write fail\n"); return 1; }    /* name.same=1 */
    if (prc_bitwrite_uint32(ctx, &ws, 1) != 0) { printf("write fail\n"); return 1; } /* tess_count=1 */
    if (prc_bitwrite_uint32(ctx, &ws, PRC_TYPE_TESS_3D_Compressed) != 0) { printf("write fail\n"); return 1; }

    /* is_calculated, has_faces, tolerance, origin: always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);                       /* is_calculated */
        prc_bitread_bit(ctx, &replay);                       /* has_faces */
        prc_bitread_double(ctx, &replay);                    /* tolerance */
        prc_bitread_float(ctx, &replay);                     /* origin.x */
        prc_bitread_float(ctx, &replay);                     /* origin.y */
        prc_bitread_float(ctx, &replay);                     /* origin.z */
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (header)\n"); return 1; }
    }

    /* point_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        uint32_t *dummy = (uint32_t *)prc_bitread_compressed_integer_array(ctx, &replay, &sz);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_POINT_ARRAY)
        {
            if (prc_bitwrite_compressed_integer_array(ctx, &ws, parsed->point_array, parsed->point_array_size) != 0)
            { printf("regen point_array failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (point_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* edge_status_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        uint8_t *dummy = prc_bitread_character_array(ctx, &replay, &sz, 2, true, 0);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_EDGE_STATUS_ARRAY)
        {
            uint32_t t_count = parsed->triangle_face_array_size;
            uint32_t padded_count = t_count * 3;
            uint8_t *padded = (uint8_t *)prc_calloc(ctx, padded_count > 0 ? padded_count : 1, sizeof(uint8_t));
            if (padded == NULL) { printf("alloc failed\n"); return 1; }
            memcpy(padded, parsed->edge_status_array, (size_t)t_count * sizeof(uint8_t));
            if (prc_bitwrite_character_array(ctx, &ws, padded, padded_count, 2, 1, 0) != 0)
            { printf("regen edge_status_array failed\n"); prc_free(ctx, padded); return 1; }
            prc_free(ctx, padded);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (edge_status_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* triangle_face_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_compressed_indice_array(ctx, &replay, &sz, 1, 0);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_TRIANGLE_FACE_ARRAY)
        {
            int32_t *tfa = (int32_t *)prc_malloc(ctx, sizeof(int32_t) * (parsed->triangle_face_array_size > 0 ? parsed->triangle_face_array_size : 1));
            for (k = 0; k < parsed->triangle_face_array_size; k++)
                tfa[k] = (int32_t)parsed->triangle_face_array[k];
            if (prc_bitwrite_compressed_indice_array(ctx, &ws, tfa, parsed->triangle_face_array_size, 1, 0) != 0)
            { printf("regen triangle_face_array failed\n"); prc_free(ctx, tfa); return 1; }
            prc_free(ctx, tfa);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (triangle_face_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* reference_array_size (uint32) + points_is_reference_array (bit loop): always verbatim */
    {
        prc_bit_state f = replay; int64_t n; uint32_t rsz;
        rsz = prc_bitread_uint32(ctx, &replay);
        for (k = 0; k < rsz; k++)
            prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (reference_array_size+bits)\n"); return 1; }
    }

    /* point_reference_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_compressed_indice_array(ctx, &replay, &sz, false, num_refs);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_POINT_REFERENCE_ARRAY)
        {
            if (prc_bitwrite_compressed_indice_array(ctx, &ws, parsed->point_reference_array,
                    parsed->point_reference_array_size, 0, num_refs) != 0)
            { printf("regen point_reference_array failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (point_reference_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* must_recalculate_normals (bit): always verbatim (known 1 for this file) */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (must_recalculate_normals)\n"); return 1; }
    }

    /* normal_is_reversed: C1-specific, plain per-triangle bit array (NOT
       Huffman-compressed -- a structurally different candidate than the
       other five fields). */
    {
        prc_bit_state f = replay; int64_t n;
        for (k = 0; k < parsed->triangle_face_array_size; k++)
            prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_NORMAL_IS_REVERSED)
        {
            for (k = 0; k < parsed->triangle_face_array_size; k++)
                if (prc_bitwrite_bit(ctx, &ws, parsed->normal_is_reversed[k]) != 0)
                { printf("regen normal_is_reversed failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (normal_is_reversed)\n"); return 1; }
        }
    }

    /* crease_angle (double) + normal_recalculation_flags (uint8): always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_double(ctx, &replay);
        prc_bitread_uint8(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (crease_angle+normal_recalculation_flags)\n"); return 1; }
    }

    /* is_point_color, is_multiple_line_attribute (both known FALSE, no sub-arrays): always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (is_point_color+is_multiple_line_attribute)\n"); return 1; }
    }

    /* line_attribute_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_short_array(ctx, &replay, &sz, true, 16);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_LINE_ATTRIBUTE_ARRAY)
        {
            int32_t *no_style_per_face = (int32_t *)prc_malloc(ctx, (size_t)face_count * sizeof(int32_t));
            memset(no_style_per_face, 0, (size_t)face_count * sizeof(int32_t));
            if (prc_bitwrite_short_array(ctx, &ws, no_style_per_face, face_count, 1, 16) != 0)
            { printf("regen line_attribute_array failed\n"); prc_free(ctx, no_style_per_face); return 1; }
            prc_free(ctx, no_style_per_face);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (line_attribute_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* no_texture, has_behaviors: always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (no_texture+has_behaviors)\n"); return 1; }
    }

    if (prc_bitwrite_flush(ctx, &ws) != 0) { printf("flush failed\n"); return 1; }

    if (prc_write_deflate(ctx, ws.buf, ws.byte_pos, &wrapper_comp, &wrapper_comp_len) != 0)
    { printf("deflate failed\n"); return 1; }
    printf("Spliced tessellation section: %zu bytes compressed, %zu bytes inflated (real was %u bytes compressed, %zu inflated)\n",
        wrapper_comp_len, ws.byte_pos, section_offsets[4] - section_offsets[3], dest_len_saved);

    /* Splice into the original file (same mechanics as reencode_real_tess.c) */
    new_section_offsets = (uint32_t *)malloc(sizeof(uint32_t) * section_count);
    for (i = 0; i <= 3; i++) new_section_offsets[i] = section_offsets[i];
    new_section_offsets[4] = section_offsets[3] + (uint32_t)wrapper_comp_len;
    {
        int32_t delta = (int32_t)new_section_offsets[4] - (int32_t)section_offsets[4];
        for (i = 5; i < section_count; i++)
            new_section_offsets[i] = (uint32_t)((int32_t)section_offsets[i] + delta);
        new_start_offset = (uint32_t)((int32_t)start_offset + delta);
        new_end_offset = (uint32_t)((int32_t)end_offset + delta);
    }
    new_total_size = (size_t)new_end_offset;

    out_buf = (uint8_t *)malloc(new_total_size);
    memcpy(out_buf, buf, header_prefix_len);
    {
        uint8_t *q = out_buf + section_off_table_byte_pos;
        size_t real_trailer_pos = section_off_table_byte_pos + (size_t)4 * section_count + 4 + 4;
        for (i = 0; i < section_count; i++) { write_le_u32(q, new_section_offsets[i]); q += 4; }
        write_le_u32(q, new_start_offset); q += 4;
        write_le_u32(q, new_end_offset); q += 4;
        memcpy(q, buf + real_trailer_pos, 4);
    }
    memcpy(out_buf + new_section_offsets[0], buf + section_offsets[0], section_offsets[3] - section_offsets[0]);
    memcpy(out_buf + new_section_offsets[3], wrapper_comp, wrapper_comp_len);
    memcpy(out_buf + new_section_offsets[4], buf + section_offsets[4], end_offset - section_offsets[4]);

    out_fid = fopen(argv[2], "wb");
    if (out_fid == NULL) { printf("failed to open output %s\n", argv[2]); return 1; }
    fwrite(out_buf, 1, new_total_size, out_fid);
    fclose(out_fid);

    printf("Wrote %s (%zu bytes)\n", argv[2], new_total_size);

    prc_free(ctx, wrapper_comp);
    prc_bitwrite_release(ctx, &ws);
    prc_api_release_context(ctx);
    free(section_offsets);
    free(new_section_offsets);
    free(out_buf);
    free(buf);
    free(tess_inflated);
    return 0;
}
