/* INTERNAL DEVELOPMENT TOOL -- not part of the permanent test suite, not
   registered with CTest, no exit-code contract to keep stable.

   WHAT: A targeted causal-isolation splicer for the Acrobat blank-model-
   tree investigation. Takes a REAL, Acrobat-working raw .prc file's
   PRC_TYPE_TESS_3D_Compressed entry and reproduces it FIELD BY FIELD,
   copying every field's raw bits verbatim from the real file EXCEPT for
   exactly one caller-selected field, which is instead regenerated fresh
   through this write facility's own production primitives
   (prc_bitwrite_character_array / prc_bitwrite_compressed_indice_array /
   prc_bitwrite_short_array, called the same way prc_write_compress_tess_
   to_stream itself calls them), fed the real, decoded values for that
   field. Everything else in the file (schema, tree, geometry, model-file,
   and every OTHER tessellation field) is left exactly as the real file has
   it. If Acrobat still rejects a file with only ONE field swapped to this
   write facility's own bit-packing, that field is implicated; if it still
   opens fine, that field is cleared.

   HOW: usage: splice_tess_field.exe <real_input.prc> <output.prc>
   [field_name]. field_name selects which single field gets regenerated by
   this write facility instead of copied verbatim; omit it (or pass
   "none") to copy every field verbatim, which should reproduce the real
   file's tessellation section bit-for-bit -- a self-check that this
   tool's field-walk is correct before trusting any non-"none" run.
   Recognized field_name values: point_array, edge_status_array,
   triangle_face_array, point_reference_array, normal_angle_array,
   line_attribute_array -- the six fields found (2026-07-10 field-level
   bit-position trace, see project notes) to differ in size between a
   zero-mutation reencode_real_tess.c re-encode and the real file, all of
   them variable-bit-width/Huffman-compressed arrays.

   WHY IT EXISTS: reencode_real_tess.c already proved that re-encoding a
   real file's tessellation entry through this write facility's writer,
   using 100% real decoded values with zero deliberate mutation, still
   produces a blank model tree in Acrobat (while working in every other
   reader tried) -- and a field-level bit-position trace showed every
   fixed-width field matches the real file bit-for-bit, with the entire
   size gap confined to six variable-bit-width array fields, all Huffman-
   compressed. Reading this write facility's Huffman table serialization
   against ISO/CD 14739-1 SS10.2 found the format structurally sound (leaf
   table field order/widths match; per-value path-bit streaming direction
   is provably correct since this write facility's own reader already
   decodes the real file's Huffman data successfully) -- so the remaining
   ~30-40% size difference looks like a different-but-valid Huffman tree
   shape, not an obvious bug. This tool tests that conclusion directly and
   causally, one field at a time, instead of reasoning about it from code
   alone: start from the known-Acrobat-good real file, swap in ONLY this
   write facility's bit-packing for one field, and see whether Acrobat
   still opens it.

   LIMITATIONS: hard-codes the field sequence and conditional branches
   (must_recalculate_normals == FALSE / C2 path; is_point_color, is_
   multiple_line_attribute, no_texture(=TRUE i.e. absent), has_behaviors
   all FALSE) matching the specific real test file this was built against
   (the hockey puck, 6503603.prc: 300 triangles, 3 faces, C2 normals, no
   point colors/multi-line-attributes/texture/behaviors) -- NOT a general
   real-file tool. A file exercising different branches (C1 normals, point
   colors, texture, behaviors) would need the field sequence extended
   before this tool could be pointed at it. Only tests one field per run;
   run it multiple times with different field_name values to bisect
   further if a single-field swap doesn't reproduce Acrobat's rejection on
   its own (which would suggest either a combination of fields, or that
   these six fields are cleared entirely and the cause lies elsewhere). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "prc_data.h"
#include "prc_api.h"
#include "prc_context.h"
#include "prc_bit.h"
#include "prc_parse_tess.h"
#include "prc_parse_common.h"
#include "prc_write_compress_tess.h"
#include "prc_write_file_structure.h"
#include "prc_write_common.h"
#include "zlib.h"

static uint32_t read_le_u32(const uint8_t *p) { return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static void write_le_u32(uint8_t *p, uint32_t v) { p[0]=(uint8_t)(v&0xff); p[1]=(uint8_t)((v>>8)&0xff); p[2]=(uint8_t)((v>>16)&0xff); p[3]=(uint8_t)((v>>24)&0xff); }

typedef enum {
    FIELD_NONE = 0,
    FIELD_POINT_ARRAY,
    FIELD_EDGE_STATUS_ARRAY,
    FIELD_TRIANGLE_FACE_ARRAY,
    FIELD_POINT_REFERENCE_ARRAY,
    FIELD_NORMAL_ANGLE_ARRAY,
    FIELD_LINE_ATTRIBUTE_ARRAY
} test_field_t;

/* Copies exactly `nbits` bits from `src` (advancing it) into `dst`, bit for
   bit, with no interpretation of the data's meaning. */
static int
copy_bits(prc_context *ctx, prc_bit_state *src, prc_bit_write_state *dst, int64_t nbits)
{
    int64_t k;
    for (k = 0; k < nbits; k++)
    {
        uint8_t bit = prc_bitread_bit(ctx, src);
        if (prc_bitwrite_bit(ctx, dst, bit) != 0)
            return -1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    prc_context *ctx;
    FILE *fid;
    long fsize;
    uint8_t *buf;
    size_t read_size;
    const uint8_t *p;
    uint32_t section_count;
    uint32_t *section_offsets;
    uint32_t start_offset, end_offset;
    uint32_t i;
    size_t header_prefix_len;
    size_t section_off_table_byte_pos;
    uint8_t *tess_inflated = NULL;
    size_t dest_len_saved = 0;
    int code;
    prc_bit_state bit_state;
    uint32_t wrapper_tag, attribute_count;
    prc_name wrapper_name;
    uint32_t tess_count;
    uint32_t entry_tag;
    prc_tess_3d_compressed *parsed = NULL;
    prc_bit_state entry_start;
    prc_bit_state replay;
    prc_bit_write_state ws;
    uint8_t *wrapper_comp = NULL;
    size_t wrapper_comp_len = 0;
    uint32_t k;
    uint32_t *new_section_offsets;
    uint32_t new_start_offset, new_end_offset;
    size_t new_total_size;
    uint8_t *out_buf;
    FILE *out_fid;
    test_field_t test_field = FIELD_NONE;
    uint32_t num_refs = 0;
    uint32_t face_count = 0;

    if (argc < 3)
    {
        printf("usage: %s <real_input.prc> <output.prc> [field_name]\n", argv[0]);
        printf("  field_name: point_array | edge_status_array | triangle_face_array |\n");
        printf("              point_reference_array | normal_angle_array | line_attribute_array\n");
        printf("  (omit or \"none\" to copy every field verbatim -- self-check mode)\n");
        return 2;
    }
    if (argc >= 4)
    {
        if (strcmp(argv[3], "point_array") == 0) test_field = FIELD_POINT_ARRAY;
        else if (strcmp(argv[3], "edge_status_array") == 0) test_field = FIELD_EDGE_STATUS_ARRAY;
        else if (strcmp(argv[3], "triangle_face_array") == 0) test_field = FIELD_TRIANGLE_FACE_ARRAY;
        else if (strcmp(argv[3], "point_reference_array") == 0) test_field = FIELD_POINT_REFERENCE_ARRAY;
        else if (strcmp(argv[3], "normal_angle_array") == 0) test_field = FIELD_NORMAL_ANGLE_ARRAY;
        else if (strcmp(argv[3], "line_attribute_array") == 0) test_field = FIELD_LINE_ATTRIBUTE_ARRAY;
        else if (strcmp(argv[3], "none") == 0) test_field = FIELD_NONE;
        else { printf("unrecognized field_name '%s'\n", argv[3]); return 2; }
    }
    printf("Test field: %s\n", argc >= 4 ? argv[3] : "none (verbatim self-check)");

    fid = fopen(argv[1], "rb");
    if (fid == NULL) { printf("failed to open %s\n", argv[1]); return 1; }
    fseek(fid, 0L, SEEK_END);
    fsize = ftell(fid);
    fseek(fid, 0L, SEEK_SET);
    buf = (uint8_t *)malloc((size_t)fsize);
    read_size = fread(buf, 1, (size_t)fsize, fid);
    fclose(fid);
    if (read_size != (size_t)fsize) { printf("short read\n"); return 1; }
    if (memcmp(buf, "PRC", 3) != 0) { printf("not a raw PRC file\n"); return 1; }

    p = buf + 3 + 4 + 4 + 16 + 16;
    if (read_le_u32(p) != 1) { printf("only single-file-structure inputs supported\n"); return 1; }
    p += 4;
    p += 16; /* fs_uid */
    p += 4;  /* reserved */
    section_off_table_byte_pos = (size_t)(p - buf) + 4;
    section_count = read_le_u32(p); p += 4;
    header_prefix_len = (size_t)(p - buf);

    section_offsets = (uint32_t *)malloc(sizeof(uint32_t) * section_count);
    for (i = 0; i < section_count; i++) { section_offsets[i] = read_le_u32(p); p += 4; }
    start_offset = read_le_u32(p); p += 4;
    end_offset = read_le_u32(p); p += 4;

    if (section_count < 4) { printf("unexpected section_count=%u\n", section_count); return 1; }

    ctx = prc_api_new_context(NULL);
    if (ctx == NULL) { printf("context creation failed\n"); return 1; }

    /* Inflate the real tessellation section (section index 3: offsets[3]..offsets[4]) */
    {
        uLongf dest_len;
        uint32_t comp_len = section_offsets[4] - section_offsets[3];
        dest_len = comp_len * 40u + 4096u;
        tess_inflated = (uint8_t *)malloc(dest_len);
        for (;;)
        {
            uLongf try_len = dest_len;
            int zret = uncompress(tess_inflated, &try_len, buf + section_offsets[3], comp_len);
            if (zret == Z_OK) { dest_len = try_len; break; }
            if (zret == Z_BUF_ERROR) { dest_len *= 2; free(tess_inflated); tess_inflated = (uint8_t *)malloc(dest_len); continue; }
            printf("zlib uncompress failed: %d\n", zret);
            return 1;
        }
        dest_len_saved = (size_t)dest_len;
        prc_init_bit_state(ctx, &bit_state, tess_inflated, (size_t)dest_len);
    }

    wrapper_tag = prc_bitread_uint32(ctx, &bit_state);
    if (wrapper_tag != PRC_TYPE_ASM_FileStructureTessellation) { printf("unexpected wrapper tag %u\n", wrapper_tag); return 1; }
    {
        prc_content_prc_base wrapper_base;
        memset(&wrapper_base, 0, sizeof(wrapper_base));
        code = prc_parse_content_prc_base(ctx, &bit_state, &wrapper_base);
        if (code < 0) { printf("prc_parse_content_prc_base failed: code=%d\n", code); return 1; }
        attribute_count = wrapper_base.attribute_data.attribute_count;
        wrapper_name = wrapper_base.name;
    }
    tess_count = prc_bitread_uint32(ctx, &bit_state);
    if (tess_count != 1) { printf("this tool only handles tess_count==1 files (got %u)\n", tess_count); return 1; }
    entry_tag = prc_bitread_uint32(ctx, &bit_state);
    if (entry_tag != PRC_TYPE_TESS_3D_Compressed) { printf("first entry is not COMPRESSED (tag=%u)\n", entry_tag); return 1; }

    /* Snapshot the read cursor right at the start of the entry body -- both
       the value-extraction pass (prc_parse_tess_3d_compressed, via
       bit_state) and the bit-boundary replay (via `replay`, below) start
       from here, independently. */
    entry_start = bit_state;

    code = prc_parse_tess_3d_compressed(ctx, &bit_state, &parsed, 0);
    if (code < 0) { printf("prc_parse_tess_3d_compressed failed: code=%d\n", code); return 1; }

    printf("Real: is_calculated=%u has_faces=%u point_array_size=%u edge_status_array_size=%u\n",
        parsed->is_calculated, parsed->has_faces, parsed->point_array_size, parsed->edge_status_array_size);
    printf("  triangle_face_array_size=%u face_number=%u reference_array_size=%u point_reference_array_size=%u\n",
        parsed->triangle_face_array_size, parsed->face_number, parsed->reference_array_size, parsed->point_reference_array_size);
    printf("  must_recalculate_normals=%u is_point_color=%u is_multiple_line_attribute=%u no_texture=%u has_behaviors=%u\n",
        parsed->must_recalculate_normals, parsed->is_point_color, parsed->is_multiple_line_attribute,
        parsed->no_texture, parsed->has_behaviors);
    if (parsed->must_recalculate_normals || parsed->is_point_color || parsed->is_multiple_line_attribute ||
        !parsed->no_texture || parsed->has_behaviors)
    {
        printf("ERROR: this real file does not match the hard-coded C2/no-extras branch this tool assumes -- see LIMITATIONS in the header comment. Aborting.\n");
        return 1;
    }
    for (k = 0; k < parsed->reference_array_size; k++)
        if (parsed->points_is_reference_array[k]) num_refs++;
    face_count = parsed->face_number;

    /* Diagnostic: print normal_angle_array's value frequency histogram. */
    {
        uint32_t distinct[64]; uint32_t dcount[64]; uint32_t ndistinct = 0, j;
        for (k = 0; k < parsed->normal_angle_array_size; k++)
        {
            int32_t v = parsed->normal_angle_array[k];
            int found = 0;
            for (j = 0; j < ndistinct; j++) if (distinct[j] == (uint32_t)v) { dcount[j]++; found = 1; break; }
            if (!found && ndistinct < 64) { distinct[ndistinct] = (uint32_t)v; dcount[ndistinct] = 1; ndistinct++; }
        }
        for (k = 0; k + 1 < ndistinct; k++)
            for (j = k + 1; j < ndistinct; j++)
                if (distinct[j] < distinct[k]) { uint32_t t=distinct[k];distinct[k]=distinct[j];distinct[j]=t; t=dcount[k];dcount[k]=dcount[j];dcount[j]=t; }
        printf("normal_angle_array histogram (distinct=%u):\n", ndistinct);
        for (k = 0; k < ndistinct; k++) printf("  value=%u freq=%u\n", distinct[k], dcount[k]);
    }

    /* Diagnostic: compute this write facility's own bit-length formula
       (1 + bits needed for magnitude, i.e. prc_int32_bit_width_signed in
       prc_write_bit.c, reproduced here since it's static/private) over the
       real, decoded point_array values, and print the distinct set --
       compare against the real file's own bit_lengths leaf-table alphabet
       to see whether the DIFFERENCE lies in which values need which
       lengths (a formula mismatch) or purely in Huffman tree shape. */
    {
        uint32_t distinct[64]; uint32_t ndistinct = 0, j;
        for (k = 0; k < parsed->point_array_size; k++)
        {
            int32_t v = parsed->point_array[k];
            uint32_t mag = (v < 0) ? (uint32_t)(-(int64_t)v) : (uint32_t)v;
            uint32_t width = 0; uint32_t mm = mag;
            while (mm != 0) { mm >>= 1; width++; }
            uint32_t bl = 1 + width;
            int found = 0;
            for (j = 0; j < ndistinct; j++) if (distinct[j] == bl) { found = 1; break; }
            if (!found && ndistinct < 64) distinct[ndistinct++] = bl;
        }
        /* simple sort */
        for (k = 0; k + 1 < ndistinct; k++)
            for (j = k + 1; j < ndistinct; j++)
                if (distinct[j] < distinct[k]) { uint32_t t = distinct[k]; distinct[k] = distinct[j]; distinct[j] = t; }
        printf("point_array bit_length formula distinct set (count=%u): ", ndistinct);
        for (k = 0; k < ndistinct; k++) printf("%u ", distinct[k]);
        printf("\n");
    }

    /* Diagnostic: inspect the real file's own edge_status_array padding
       region [triangle_face_array_size, edge_status_array_size) -- CR-14
       leaves the exact 3T padding convention undetermined in the draft ISO
       spec text; check empirically whether the real encoder used simple
       zero-padding (matching this write facility's assumption) or
       something else. */
    {
        uint32_t t = parsed->triangle_face_array_size;
        uint32_t nonzero_pad = 0, first_nonzero_idx = 0xFFFFFFFFu;
        uint32_t hist[4] = {0,0,0,0};
        printf("edge_status_array real values [0..%u): ", t < 20 ? t : 20);
        for (k = 0; k < t && k < 20; k++) printf("%u ", parsed->edge_status_array[k]);
        printf("...\n");
        for (k = 0; k < t; k++)
        {
            uint8_t v = parsed->edge_status_array[k];
            if (v < 4) hist[v]++;
        }
        printf("edge_status_array [0..%u) value histogram: 0=%u 1=%u 2=%u 3=%u\n",
            t, hist[0], hist[1], hist[2], hist[3]);
        for (k = t; k < parsed->edge_status_array_size; k++)
        {
            if (parsed->edge_status_array[k] != 0)
            {
                nonzero_pad++;
                if (first_nonzero_idx == 0xFFFFFFFFu) first_nonzero_idx = k;
            }
        }
        printf("edge_status_array padding region [%u..%u): nonzero_count=%u first_nonzero_idx=%u\n",
            t, parsed->edge_status_array_size, nonzero_pad,
            first_nonzero_idx == 0xFFFFFFFFu ? 0 : first_nonzero_idx);
    }

    /* ---- Field-by-field replay + splice ---- */
    replay = entry_start;
    memset(&ws, 0, sizeof(ws));
    if (prc_bitwrite_init(ctx, &ws, 4096) != 0) { printf("wrapper init failed\n"); return 1; }
    if (prc_bitwrite_uint32(ctx, &ws, PRC_TYPE_ASM_FileStructureTessellation) != 0) { printf("write fail\n"); return 1; }
    if (prc_bitwrite_uint32(ctx, &ws, 0) != 0) { printf("write fail\n"); return 1; } /* attribute_count=0, matches real (checked implicitly: attribute_count var unused beyond this note) */
    if (prc_bitwrite_bit(ctx, &ws, 1) != 0) { printf("write fail\n"); return 1; }    /* name.same=1 */
    if (prc_bitwrite_uint32(ctx, &ws, 1) != 0) { printf("write fail\n"); return 1; } /* tess_count=1 */
    if (prc_bitwrite_uint32(ctx, &ws, PRC_TYPE_TESS_3D_Compressed) != 0) { printf("write fail\n"); return 1; }

    /* is_calculated, has_faces, tolerance, origin: always verbatim (already
       confirmed bit-identical between real and reencode_real_tess.c's
       output; not in the candidate field list, and not worth a code path
       to regenerate). */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);                       /* is_calculated */
        prc_bitread_bit(ctx, &replay);                       /* has_faces */
        prc_bitread_double(ctx, &replay);                    /* tolerance */
        prc_bitread_float(ctx, &replay);                     /* origin.x */
        prc_bitread_float(ctx, &replay);                     /* origin.y */
        prc_bitread_float(ctx, &replay);                     /* origin.z */
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (header)\n"); return 1; }
    }

    /* point_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        uint32_t *dummy = (uint32_t *)prc_bitread_compressed_integer_array(ctx, &replay, &sz);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_POINT_ARRAY)
        {
            if (prc_bitwrite_compressed_integer_array(ctx, &ws, parsed->point_array, parsed->point_array_size) != 0)
            { printf("regen point_array failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (point_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* edge_status_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        uint8_t *dummy = prc_bitread_character_array(ctx, &replay, &sz, 2, true, 0);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_EDGE_STATUS_ARRAY)
        {
            uint32_t t_count = parsed->triangle_face_array_size;
            uint32_t padded_count = t_count * 3;
            uint8_t *padded = (uint8_t *)prc_calloc(ctx, padded_count > 0 ? padded_count : 1, sizeof(uint8_t));
            if (padded == NULL) { printf("alloc failed\n"); return 1; }
            memcpy(padded, parsed->edge_status_array, (size_t)t_count * sizeof(uint8_t));
            if (prc_bitwrite_character_array(ctx, &ws, padded, padded_count, 2, 1, 0) != 0)
            { printf("regen edge_status_array failed\n"); prc_free(ctx, padded); return 1; }
            prc_free(ctx, padded);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (edge_status_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* triangle_face_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_compressed_indice_array(ctx, &replay, &sz, 1, 0);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_TRIANGLE_FACE_ARRAY)
        {
            int32_t *tfa = (int32_t *)prc_malloc(ctx, sizeof(int32_t) * (parsed->triangle_face_array_size > 0 ? parsed->triangle_face_array_size : 1));
            for (k = 0; k < parsed->triangle_face_array_size; k++)
                tfa[k] = (int32_t)parsed->triangle_face_array[k];
            if (prc_bitwrite_compressed_indice_array(ctx, &ws, tfa, parsed->triangle_face_array_size, 1, 0) != 0)
            { printf("regen triangle_face_array failed\n"); prc_free(ctx, tfa); return 1; }
            prc_free(ctx, tfa);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (triangle_face_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* reference_array_size (uint32) + points_is_reference_array (bit loop): always verbatim */
    {
        prc_bit_state f = replay; int64_t n; uint32_t rsz;
        rsz = prc_bitread_uint32(ctx, &replay);
        for (k = 0; k < rsz; k++)
            prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (reference_array_size+bits)\n"); return 1; }
    }

    /* point_reference_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_compressed_indice_array(ctx, &replay, &sz, false, num_refs);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_POINT_REFERENCE_ARRAY)
        {
            if (prc_bitwrite_compressed_indice_array(ctx, &ws, parsed->point_reference_array,
                    parsed->point_reference_array_size, 0, num_refs) != 0)
            { printf("regen point_reference_array failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (point_reference_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* must_recalculate_normals (bit): always verbatim (known 0 for this file) */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (must_recalculate_normals)\n"); return 1; }
    }

    /* normal_angle_number_of_bits, normal_binary_data_size, normal_binary_data: always verbatim */
    {
        prc_bit_state f = replay; int64_t n; uint32_t nbds; uint8_t nab;
        nab = prc_bitread_uint8(ctx, &replay);
        nbds = prc_bitread_uint32(ctx, &replay);
        for (k = 0; k < nbds; k++)
            prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (normal_angle_number_of_bits+normal_binary_data)\n"); return 1; }
        (void)nab;
    }

    /* normal_angle_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_short_array(ctx, &replay, &sz, true, parsed->normal_angle_number_of_bits);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_NORMAL_ANGLE_ARRAY)
        {
            if (prc_bitwrite_short_array(ctx, &ws, parsed->normal_angle_array,
                    parsed->normal_angle_array_size, 1, parsed->normal_angle_number_of_bits) != 0)
            { printf("regen normal_angle_array failed\n"); return 1; }
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (normal_angle_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* is_face_planar (face_count bits): always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        for (k = 0; k < face_count; k++)
            prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (is_face_planar)\n"); return 1; }
    }

    /* is_point_color, is_multiple_line_attribute (both known FALSE, no sub-arrays): always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (is_point_color+is_multiple_line_attribute)\n"); return 1; }
    }

    /* line_attribute_array */
    {
        prc_bit_state f = replay; int64_t n; uint32_t sz;
        int32_t *dummy = prc_bitread_short_array(ctx, &replay, &sz, true, 16);
        n = replay.bit_position - f.bit_position;
        if (test_field == FIELD_LINE_ATTRIBUTE_ARRAY)
        {
            int32_t *no_style_per_face = (int32_t *)prc_malloc(ctx, (size_t)face_count * sizeof(int32_t));
            memset(no_style_per_face, 0, (size_t)face_count * sizeof(int32_t));
            if (prc_bitwrite_short_array(ctx, &ws, no_style_per_face, face_count, 1, 16) != 0)
            { printf("regen line_attribute_array failed\n"); prc_free(ctx, no_style_per_face); return 1; }
            prc_free(ctx, no_style_per_face);
        }
        else
        {
            if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (line_attribute_array)\n"); return 1; }
        }
        (void)dummy;
    }

    /* no_texture, has_behaviors (both known TRUE/FALSE respectively, no sub-content): always verbatim */
    {
        prc_bit_state f = replay; int64_t n;
        prc_bitread_bit(ctx, &replay);
        prc_bitread_bit(ctx, &replay);
        n = replay.bit_position - f.bit_position;
        if (copy_bits(ctx, &f, &ws, n) != 0) { printf("copy failed (no_texture+has_behaviors)\n"); return 1; }
    }

    if (prc_bitwrite_flush(ctx, &ws) != 0) { printf("flush failed\n"); return 1; }

    if (prc_write_deflate(ctx, ws.buf, ws.byte_pos, &wrapper_comp, &wrapper_comp_len) != 0)
    { printf("deflate failed\n"); return 1; }
    printf("Spliced tessellation section: %zu bytes compressed, %zu bytes inflated (real was %u bytes compressed, %zu inflated)\n",
        wrapper_comp_len, ws.byte_pos, section_offsets[4] - section_offsets[3], dest_len_saved);

    /* Splice into the original file (same mechanics as reencode_real_tess.c) */
    new_section_offsets = (uint32_t *)malloc(sizeof(uint32_t) * section_count);
    for (i = 0; i <= 3; i++) new_section_offsets[i] = section_offsets[i];
    new_section_offsets[4] = section_offsets[3] + (uint32_t)wrapper_comp_len;
    {
        int32_t delta = (int32_t)new_section_offsets[4] - (int32_t)section_offsets[4];
        for (i = 5; i < section_count; i++)
            new_section_offsets[i] = (uint32_t)((int32_t)section_offsets[i] + delta);
        new_start_offset = (uint32_t)((int32_t)start_offset + delta);
        new_end_offset = (uint32_t)((int32_t)end_offset + delta);
    }
    new_total_size = (size_t)new_end_offset;

    out_buf = (uint8_t *)malloc(new_total_size);
    memcpy(out_buf, buf, header_prefix_len);
    {
        uint8_t *q = out_buf + section_off_table_byte_pos;
        size_t real_trailer_pos = section_off_table_byte_pos + (size_t)4 * section_count + 4 + 4;
        for (i = 0; i < section_count; i++) { write_le_u32(q, new_section_offsets[i]); q += 4; }
        write_le_u32(q, new_start_offset); q += 4;
        write_le_u32(q, new_end_offset); q += 4;
        memcpy(q, buf + real_trailer_pos, 4);
    }
    memcpy(out_buf + new_section_offsets[0], buf + section_offsets[0], section_offsets[3] - section_offsets[0]);
    memcpy(out_buf + new_section_offsets[3], wrapper_comp, wrapper_comp_len);
    memcpy(out_buf + new_section_offsets[4], buf + section_offsets[4], end_offset - section_offsets[4]);

    out_fid = fopen(argv[2], "wb");
    if (out_fid == NULL) { printf("failed to open output %s\n", argv[2]); return 1; }
    fwrite(out_buf, 1, new_total_size, out_fid);
    fclose(out_fid);

    printf("Wrote %s (%zu bytes)\n", argv[2], new_total_size);

    prc_free(ctx, wrapper_comp);
    prc_bitwrite_release(ctx, &ws);
    prc_api_release_context(ctx);
    free(section_offsets);
    free(new_section_offsets);
    free(out_buf);
    free(buf);
    free(tess_inflated);
    return 0;
}
